// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview A slang definition AI agent.
 *
 * - defineSlang - A function that handles the slang definition process.
 * - DefineSlangInput - The input type for the defineSlang function.
 * - DefineSlangOutput - The return type for the defineSlang function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const DefineSlangInputSchema = z.object({
  slangWord: z.string().describe('The slang word to define.'),
});
export type DefineSlangInput = z.infer<typeof DefineSlangInputSchema>;

const DefineSlangOutputSchema = z.object({
  definition: z.string().describe('The definition of the slang word.'),
  confidence: z.number().describe('The confidence level in the definition (0-1).'),
  source: z.string().describe('The source of the definition.'),
});
export type DefineSlangOutput = z.infer<typeof DefineSlangOutputSchema>;

export async function defineSlang(input: DefineSlangInput): Promise<DefineSlangOutput> {
  return defineSlangFlow(input);
}

const defineSlangPrompt = ai.definePrompt({
  name: 'defineSlangPrompt',
  input: {schema: DefineSlangInputSchema},
  output: {schema: DefineSlangOutputSchema},
  prompt: `You are an expert in slang terminology. Define the following slang word, provide a confidence level (0-1) for the definition, and provide the source of the definition.\n\nSlang word: {{{slangWord}}}`,
});

const defineSlangFlow = ai.defineFlow(
  {
    name: 'defineSlangFlow',
    inputSchema: DefineSlangInputSchema,
    outputSchema: DefineSlangOutputSchema,
  },
  async input => {
    const {output} = await defineSlangPrompt(input);
    return output!;
  }
);
